### ISSUE TITLE
Minor update in Name To Use

### ISSUE THREAD

**Issue by snichols001** [rjhorniii/dicom-sup233-wip#1]
In Sup233-Patient Model Gender Enhancements-20230424, reword line 532 to read "This may require modification of SOP Instances in order to preserve the restriction that these have the same value for all SOP Instances for that patient for consistency with Modified Attributes Sequence (0400,0550)"

**Comment by rjhorniii** [comment]
Slightly revised wording applied, plus another clarification regarding Patient Root and Study Root.
